version: '3.7'

services:
  db:
    restart: unless-stopped
    image: postgres:12.2-alpine
    env_file:
      - .env
  api:
    restart: unless-stopped
    build:
      context: ./backend
      target: dev
    env_file:
      - .env
    command: bash -c "python3 /api/src/manage.py collectstatic --noinput &&
            python3 /api/src/manage.py migrate &&
            uwsgi --ini /api/src/uwsgi.ini"
    volumes:
      - ./backend/:/api/src/
    depends_on:
      - db
  nginx-proxy:
    restart: unless-stopped
    image: nginx:1.17.9-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/local_nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
